version: "3.9"

volumes:
  models:
    name: models
  app_dir:
    name: app_dir

services:
  sd_client:
    build: .
    volumes:
      - app_dir:/usr/local/share/sd_client
      - models:/root/.cache/huggingface:rw
    environment:
      SD_API_URL: "https://ai.posterity.no"
      SD_TEST_MODE: 0
      SD_CPU_MODE: 1
    stdin_open: true
    tty: true
