version: "3.9"

volumes:
  models:
    name: models

services:
  sd_client:
    build: .
    volumes:
      - .:/usr/local/share/sd_client
      - models:/root/.cache/huggingface:rw
    environment:
      SD_API_URL: "http://127.0.0.1:5000"
      SD_TEST_MODE: 1
      SD_CPU_MODE: 1
