version: "3.9"

volumes:
  models:
    name: models
  torch-cache:
    name: torch-cache
  ff-cache:
    name: ff-cache
  im-cache:
    name: im-cache

services:
  sd_client:
    build: .
    volumes:
      - models:/root/.cache/huggingface:rwx
      - torch-cache:/root/.cache/torch:rwx
      - ff-cache:/usr/local/lib/python3.10/site-packages/facexlib/weights:rwx
      - im-cache:/root/.cache/imaginairy:rwx
    env_file: .env
    environment:
      NVIDIA_DISABLE_REQUIRE: 1
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
