version: "3.9"

volumes:
  models:
    name: models
  torch-cache:
    name: torch-cache
  ff-cache:
    name: ff-cache
  im-cache:
    name: im-cache

services:
  sd_client:
    build: .
    volumes:
      - models:/root/.cache/huggingface:rw
      - torch-cache:/root/.cache/torch:rw
      - ff-cache:/usr/local/lib/python3.10/site-packages/facexlib/weights:rw
      - im-cache:/root/.cache/imaginairy:rw
    env_file: .env
    environment:
      NVIDIA_DISABLE_REQUIRE: 1
    stdin_open: true
    tty: true
    restart: always
    deploy:
      resources:
        #limits:
        #  memory: 8G
        reservations:
        #  memory: 6G
          devices:
          - driver: nvidia
            capabilities: [gpu]
